### ISSUE TITLE
请问这里的文档还更新吗

### ISSUE THREAD

**Issue by alick** [haiwen/seafile-docs-cn#106]
最近的更新是两年前了。https://cloud.seafile.com/published/seafile-manual-cn/deploy/using_sqlite.md 里面的安装依赖看起来好像过时了

**Comment by freeplant** [comment]
这里的文档不更新了。新的文档在 https://cloud.seafile.com/published/seafile-manual-cn/

而且 using sqlite 已经不推荐了。
